// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vehicle_Backend;

#nullable disable

namespace Vehicle_Backend.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240729185336_updated-servicerecod")]
    partial class updatedservicerecod
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRecordId")
                        .HasColumnType("int");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRecordId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ServiceItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 1,
                            ServiceRecordId = 1,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 2,
                            ServiceRecordId = 1,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 1,
                            ServiceRecordId = 2,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 4,
                            Quantity = 3,
                            ServiceRecordId = 2,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 5,
                            Quantity = 2,
                            ServiceRecordId = 3,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 6,
                            Quantity = 1,
                            ServiceRecordId = 3,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 7,
                            Quantity = 1,
                            ServiceRecordId = 4,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 8,
                            Quantity = 2,
                            ServiceRecordId = 4,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 9,
                            Quantity = 3,
                            ServiceRecordId = 5,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 10,
                            Quantity = 2,
                            ServiceRecordId = 5,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 11,
                            Quantity = 2,
                            ServiceRecordId = 6,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 12,
                            Quantity = 1,
                            ServiceRecordId = 6,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 13,
                            Quantity = 1,
                            ServiceRecordId = 7,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 14,
                            Quantity = 3,
                            ServiceRecordId = 7,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 15,
                            Quantity = 2,
                            ServiceRecordId = 8,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 16,
                            Quantity = 1,
                            ServiceRecordId = 8,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 17,
                            Quantity = 3,
                            ServiceRecordId = 9,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 18,
                            Quantity = 2,
                            ServiceRecordId = 9,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 19,
                            Quantity = 2,
                            ServiceRecordId = 10,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 20,
                            Quantity = 1,
                            ServiceRecordId = 10,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 21,
                            Quantity = 1,
                            ServiceRecordId = 11,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 22,
                            Quantity = 2,
                            ServiceRecordId = 11,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 23,
                            Quantity = 3,
                            ServiceRecordId = 12,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 24,
                            Quantity = 2,
                            ServiceRecordId = 12,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 25,
                            Quantity = 2,
                            ServiceRecordId = 13,
                            WorkItemId = 1
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceAdvisorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAdvisorId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScheduledDate = new DateTime(2024, 8, 6, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3185),
                            ServiceAdvisorId = 3,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedDate = new DateTime(2024, 7, 25, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3191),
                            ScheduledDate = new DateTime(2024, 7, 20, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3190),
                            ServiceAdvisorId = 3,
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ScheduledDate = new DateTime(2024, 8, 13, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3195),
                            ServiceAdvisorId = 3,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 4,
                            ScheduledDate = new DateTime(2024, 8, 2, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3197),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            ScheduledDate = new DateTime(2024, 8, 19, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3199),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ScheduledDate = new DateTime(2024, 7, 31, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3201),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ScheduledDate = new DateTime(2024, 8, 6, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3203),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompletedDate = new DateTime(2024, 7, 15, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3206),
                            ScheduledDate = new DateTime(2024, 7, 10, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3205),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ScheduledDate = new DateTime(2024, 8, 11, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3208),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 10,
                            ScheduledDate = new DateTime(2024, 8, 29, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3210),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ScheduledDate = new DateTime(2024, 8, 4, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3212),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 12,
                            ScheduledDate = new DateTime(2024, 8, 7, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3214),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 13,
                            CompletedDate = new DateTime(2024, 7, 27, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3217),
                            ScheduledDate = new DateTime(2024, 7, 22, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3216),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 14,
                            ScheduledDate = new DateTime(2024, 8, 9, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3219),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 15,
                            ScheduledDate = new DateTime(2024, 8, 1, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3221),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 16,
                            ScheduledDate = new DateTime(2024, 8, 8, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3224),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 17,
                            CompletedDate = new DateTime(2024, 7, 30, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3227),
                            ScheduledDate = new DateTime(2024, 7, 25, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3226),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 18,
                            ScheduledDate = new DateTime(2024, 8, 14, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3229),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 19,
                            ScheduledDate = new DateTime(2024, 8, 10, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3230),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 20,
                            ScheduledDate = new DateTime(2024, 8, 24, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3233),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 21,
                            ScheduledDate = new DateTime(2024, 8, 5, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3235),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 22,
                            ScheduledDate = new DateTime(2024, 8, 3, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3237),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 23,
                            CompletedDate = new DateTime(2024, 7, 23, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3240),
                            ScheduledDate = new DateTime(2024, 7, 18, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3239),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 24,
                            ScheduledDate = new DateTime(2024, 8, 17, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3242),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 25,
                            ScheduledDate = new DateTime(2024, 8, 12, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(3244),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2023, 11, 1, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "",
                            MobileNumber = "1234567890",
                            Password = "admin",
                            UserType = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 7, 30, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2464),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            MobileNumber = "0987654321",
                            Password = "password",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 3,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 7, 20, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2479),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            MobileNumber = "2345678901",
                            Password = "password123",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 4,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 7, 25, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2486),
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            MobileNumber = "3456789012",
                            Password = "password456",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 5,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 7, 15, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2489),
                            Email = "michael.williams@example.com",
                            FirstName = "Michael",
                            LastName = "Williams",
                            MobileNumber = "4567890123",
                            Password = "password789",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 6,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 7, 10, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2492),
                            Email = "sarah.brown@example.com",
                            FirstName = "Sarah",
                            LastName = "Brown",
                            MobileNumber = "5678901234",
                            Password = "password987",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 7,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 7, 5, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2495),
                            Email = "david.davis@example.com",
                            FirstName = "David",
                            LastName = "Davis",
                            MobileNumber = "6789012345",
                            Password = "password654",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 8,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 6, 30, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2498),
                            Email = "laura.wilson@example.com",
                            FirstName = "Laura",
                            LastName = "Wilson",
                            MobileNumber = "7890123456",
                            Password = "password321",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 9,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 6, 25, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2501),
                            Email = "daniel.moore@example.com",
                            FirstName = "Daniel",
                            LastName = "Moore",
                            MobileNumber = "8901234567",
                            Password = "password246",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 10,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 6, 20, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2504),
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            MobileNumber = "9012345678",
                            Password = "password135",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 11,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 6, 15, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2507),
                            Email = "ethan.anderson@example.com",
                            FirstName = "Ethan",
                            LastName = "Anderson",
                            MobileNumber = "0123456789",
                            Password = "password864",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 12,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 6, 10, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2509),
                            Email = "ava.thomas@example.com",
                            FirstName = "Ava",
                            LastName = "Thomas",
                            MobileNumber = "1234567890",
                            Password = "password753",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 13,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 6, 5, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2512),
                            Email = "james.jackson@example.com",
                            FirstName = "James",
                            LastName = "Jackson",
                            MobileNumber = "2345678901",
                            Password = "password642",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 14,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 5, 31, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2515),
                            Email = "isabella.white@example.com",
                            FirstName = "Isabella",
                            LastName = "White",
                            MobileNumber = "3456789012",
                            Password = "password531",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 15,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 5, 26, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2517),
                            Email = "benjamin.harris@example.com",
                            FirstName = "Benjamin",
                            LastName = "Harris",
                            MobileNumber = "4567890123",
                            Password = "password420",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 16,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 5, 21, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2520),
                            Email = "sophia.martin@example.com",
                            FirstName = "Sophia",
                            LastName = "Martin",
                            MobileNumber = "5678901234",
                            Password = "password309",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 17,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 5, 16, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2524),
                            Email = "jackson.thompson@example.com",
                            FirstName = "Jackson",
                            LastName = "Thompson",
                            MobileNumber = "6789012345",
                            Password = "password198",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 18,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 5, 11, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2527),
                            Email = "mia.garcia@example.com",
                            FirstName = "Mia",
                            LastName = "Garcia",
                            MobileNumber = "7890123456",
                            Password = "password987",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 19,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 5, 6, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2530),
                            Email = "alexander.martinez@example.com",
                            FirstName = "Alexander",
                            LastName = "Martinez",
                            MobileNumber = "8901234567",
                            Password = "password876",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 20,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 5, 1, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2533),
                            Email = "charlotte.roberts@example.com",
                            FirstName = "Charlotte",
                            LastName = "Roberts",
                            MobileNumber = "9012345678",
                            Password = "password765",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 21,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 4, 26, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2535),
                            Email = "henry.lee@example.com",
                            FirstName = "Henry",
                            LastName = "Lee",
                            MobileNumber = "0123456789",
                            Password = "password654",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 22,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 4, 21, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2538),
                            Email = "amelia.perez@example.com",
                            FirstName = "Amelia",
                            LastName = "Perez",
                            MobileNumber = "1234567890",
                            Password = "password543",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 23,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 4, 16, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2541),
                            Email = "sebastian.young@example.com",
                            FirstName = "Sebastian",
                            LastName = "Young",
                            MobileNumber = "2345678901",
                            Password = "password432",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 24,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 4, 11, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2543),
                            Email = "harper.walker@example.com",
                            FirstName = "Harper",
                            LastName = "Walker",
                            MobileNumber = "3456789012",
                            Password = "password321",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 25,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 4, 6, 0, 23, 35, 166, DateTimeKind.Local).AddTicks(2546),
                            Email = "oliver.hall@example.com",
                            FirstName = "Oliver",
                            LastName = "Hall",
                            MobileNumber = "4567890123",
                            Password = "password210",
                            UserType = "SERVICE_ADVISOR"
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "ABC123",
                            Model = "Model X",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "XYZ789",
                            Model = "Model Y",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "LMN456",
                            Model = "Model Z",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            LicensePlate = "PQR012",
                            Model = "Model A",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            LicensePlate = "STU345",
                            Model = "Model B",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 6,
                            LicensePlate = "VWX678",
                            Model = "Model C",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 7,
                            LicensePlate = "YZA901",
                            Model = "Model D",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 8,
                            LicensePlate = "BCD234",
                            Model = "Model E",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 9,
                            LicensePlate = "EFG567",
                            Model = "Model F",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 10,
                            LicensePlate = "HIJ890",
                            Model = "Model G",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 11,
                            LicensePlate = "KLM123",
                            Model = "Model H",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 12,
                            LicensePlate = "NOP456",
                            Model = "Model I",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 13,
                            LicensePlate = "QRS789",
                            Model = "Model J",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 14,
                            LicensePlate = "TUV012",
                            Model = "Model K",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 15,
                            LicensePlate = "WXY345",
                            Model = "Model L",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 16,
                            LicensePlate = "ZAB678",
                            Model = "Model M",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 17,
                            LicensePlate = "CDE901",
                            Model = "Model N",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 18,
                            LicensePlate = "FGH234",
                            Model = "Model O",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 19,
                            LicensePlate = "IJK567",
                            Model = "Model P",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 20,
                            LicensePlate = "LMN890",
                            Model = "Model Q",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 21,
                            LicensePlate = "OPQ123",
                            Model = "Model R",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 22,
                            LicensePlate = "RST456",
                            Model = "Model S",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 23,
                            LicensePlate = "UVW789",
                            Model = "Model T",
                            OwnerId = 13
                        },
                        new
                        {
                            Id = 24,
                            LicensePlate = "XYZ012",
                            Model = "Model U",
                            OwnerId = 13
                        },
                        new
                        {
                            Id = 25,
                            LicensePlate = "ABC345",
                            Model = "Model V",
                            OwnerId = 14
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 30.00m,
                            Name = "Oil Change"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 40.00m,
                            Name = "Tire Rotation"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 50.00m,
                            Name = "Brake Inspection"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 70.00m,
                            Name = "Battery Replacement"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 120.00m,
                            Name = "Engine Tune-Up"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 150.00m,
                            Name = "Transmission Service"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 60.00m,
                            Name = "Alignment"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 20.00m,
                            Name = "Filter Replacement"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 25.00m,
                            Name = "Fluid Check"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 80.00m,
                            Name = "Suspension Check"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 45.00m,
                            Name = "Headlight Replacement"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 35.00m,
                            Name = "Tail Light Replacement"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 100.00m,
                            Name = "Air Conditioning Service"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 55.00m,
                            Name = "Radiator Flush"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 75.00m,
                            Name = "Power Steering Service"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 40.00m,
                            Name = "Serpentine Belt Replacement"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 90.00m,
                            Name = "Water Pump Replacement"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 200.00m,
                            Name = "Timing Belt Replacement"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 85.00m,
                            Name = "Exhaust System Check"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 95.00m,
                            Name = "Differential Service"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 25.00m,
                            Name = "Windshield Wiper Replacement"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 50.00m,
                            Name = "Rear Window Defogger Repair"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 15.00m,
                            Name = "Fuse Replacement"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 100.00m,
                            Name = "Wheel Bearing Replacement"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 180.00m,
                            Name = "Turbocharger Service"
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceItem", b =>
                {
                    b.HasOne("Vehicle_Backend.Models.ServiceRecord", "ServiceRecord")
                        .WithMany()
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicle_Backend.Models.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRecord");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceRecord", b =>
                {
                    b.HasOne("Vehicle_Backend.Models.User", "ServiceAdvisor")
                        .WithMany()
                        .HasForeignKey("ServiceAdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vehicle_Backend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceAdvisor");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
