// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Vehicle_Backend;

#nullable disable

namespace Vehicle_Backend.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20240729172031_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int>("ServiceRecordId")
                        .HasColumnType("int");

                    b.Property<int>("WorkItemId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceRecordId");

                    b.HasIndex("WorkItemId");

                    b.ToTable("ServiceItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Quantity = 1,
                            ServiceRecordId = 1,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 2,
                            Quantity = 2,
                            ServiceRecordId = 1,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 3,
                            Quantity = 1,
                            ServiceRecordId = 2,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 4,
                            Quantity = 3,
                            ServiceRecordId = 2,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 5,
                            Quantity = 2,
                            ServiceRecordId = 3,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 6,
                            Quantity = 1,
                            ServiceRecordId = 3,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 7,
                            Quantity = 1,
                            ServiceRecordId = 4,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 8,
                            Quantity = 2,
                            ServiceRecordId = 4,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 9,
                            Quantity = 3,
                            ServiceRecordId = 5,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 10,
                            Quantity = 2,
                            ServiceRecordId = 5,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 11,
                            Quantity = 2,
                            ServiceRecordId = 6,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 12,
                            Quantity = 1,
                            ServiceRecordId = 6,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 13,
                            Quantity = 1,
                            ServiceRecordId = 7,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 14,
                            Quantity = 3,
                            ServiceRecordId = 7,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 15,
                            Quantity = 2,
                            ServiceRecordId = 8,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 16,
                            Quantity = 1,
                            ServiceRecordId = 8,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 17,
                            Quantity = 3,
                            ServiceRecordId = 9,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 18,
                            Quantity = 2,
                            ServiceRecordId = 9,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 19,
                            Quantity = 2,
                            ServiceRecordId = 10,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 20,
                            Quantity = 1,
                            ServiceRecordId = 10,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 21,
                            Quantity = 1,
                            ServiceRecordId = 11,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 22,
                            Quantity = 2,
                            ServiceRecordId = 11,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 23,
                            Quantity = 3,
                            ServiceRecordId = 12,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 24,
                            Quantity = 2,
                            ServiceRecordId = 12,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 25,
                            Quantity = 2,
                            ServiceRecordId = 13,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 26,
                            Quantity = 1,
                            ServiceRecordId = 13,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 27,
                            Quantity = 1,
                            ServiceRecordId = 14,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 28,
                            Quantity = 3,
                            ServiceRecordId = 14,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 29,
                            Quantity = 2,
                            ServiceRecordId = 15,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 30,
                            Quantity = 1,
                            ServiceRecordId = 15,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 31,
                            Quantity = 1,
                            ServiceRecordId = 16,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 32,
                            Quantity = 2,
                            ServiceRecordId = 16,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 33,
                            Quantity = 3,
                            ServiceRecordId = 17,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 34,
                            Quantity = 2,
                            ServiceRecordId = 17,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 35,
                            Quantity = 2,
                            ServiceRecordId = 18,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 36,
                            Quantity = 1,
                            ServiceRecordId = 18,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 37,
                            Quantity = 1,
                            ServiceRecordId = 19,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 38,
                            Quantity = 2,
                            ServiceRecordId = 19,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 39,
                            Quantity = 3,
                            ServiceRecordId = 20,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 40,
                            Quantity = 2,
                            ServiceRecordId = 20,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 41,
                            Quantity = 2,
                            ServiceRecordId = 21,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 42,
                            Quantity = 1,
                            ServiceRecordId = 21,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 43,
                            Quantity = 1,
                            ServiceRecordId = 22,
                            WorkItemId = 1
                        },
                        new
                        {
                            Id = 44,
                            Quantity = 3,
                            ServiceRecordId = 22,
                            WorkItemId = 2
                        },
                        new
                        {
                            Id = 45,
                            Quantity = 2,
                            ServiceRecordId = 23,
                            WorkItemId = 1
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("CompletedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ScheduledDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceAdvisorId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int>("VehicleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ServiceAdvisorId");

                    b.HasIndex("VehicleId");

                    b.ToTable("ServiceRecords", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ScheduledDate = new DateTime(2024, 8, 5, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5596),
                            ServiceAdvisorId = 3,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 2,
                            CompletedDate = new DateTime(2024, 7, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5599),
                            ScheduledDate = new DateTime(2024, 7, 19, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5598),
                            ServiceAdvisorId = 3,
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 3,
                            ScheduledDate = new DateTime(2024, 8, 12, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5603),
                            ServiceAdvisorId = 3,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 4,
                            ScheduledDate = new DateTime(2024, 8, 1, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5604),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 5,
                            ScheduledDate = new DateTime(2024, 8, 18, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5606),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 6,
                            ScheduledDate = new DateTime(2024, 7, 30, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5607),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 7,
                            ScheduledDate = new DateTime(2024, 8, 5, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5609),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 8,
                            CompletedDate = new DateTime(2024, 7, 14, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5611),
                            ScheduledDate = new DateTime(2024, 7, 9, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5610),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 9,
                            ScheduledDate = new DateTime(2024, 8, 10, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5612),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 10,
                            ScheduledDate = new DateTime(2024, 8, 28, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5614),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 11,
                            ScheduledDate = new DateTime(2024, 8, 3, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5616),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 12,
                            ScheduledDate = new DateTime(2024, 8, 6, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5617),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 13,
                            CompletedDate = new DateTime(2024, 7, 26, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5620),
                            ScheduledDate = new DateTime(2024, 7, 21, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5619),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 14,
                            ScheduledDate = new DateTime(2024, 8, 8, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5621),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 15,
                            ScheduledDate = new DateTime(2024, 7, 31, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5622),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 16,
                            ScheduledDate = new DateTime(2024, 8, 7, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5624),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 17,
                            CompletedDate = new DateTime(2024, 7, 29, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5626),
                            ScheduledDate = new DateTime(2024, 7, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5625),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 18,
                            ScheduledDate = new DateTime(2024, 8, 13, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5627),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 19,
                            ScheduledDate = new DateTime(2024, 8, 9, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5628),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 20,
                            ScheduledDate = new DateTime(2024, 8, 23, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5630),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 21,
                            ScheduledDate = new DateTime(2024, 8, 4, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5631),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 22,
                            ScheduledDate = new DateTime(2024, 8, 2, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5632),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 23,
                            CompletedDate = new DateTime(2024, 7, 22, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5634),
                            ScheduledDate = new DateTime(2024, 7, 17, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5633),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 24,
                            ScheduledDate = new DateTime(2024, 8, 16, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5636),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 25,
                            ScheduledDate = new DateTime(2024, 8, 11, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5637),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 26,
                            ScheduledDate = new DateTime(2024, 8, 20, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5638),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 27,
                            ScheduledDate = new DateTime(2024, 8, 5, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5640),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 28,
                            ScheduledDate = new DateTime(2024, 8, 4, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5642),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 29,
                            CompletedDate = new DateTime(2024, 7, 31, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5644),
                            ScheduledDate = new DateTime(2024, 7, 26, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5643),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 30,
                            ScheduledDate = new DateTime(2024, 8, 19, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5645),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 31,
                            ScheduledDate = new DateTime(2024, 8, 7, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5646),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 32,
                            ScheduledDate = new DateTime(2024, 8, 21, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5648),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 33,
                            ScheduledDate = new DateTime(2024, 8, 6, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5649),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 34,
                            ScheduledDate = new DateTime(2024, 8, 3, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6180),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 35,
                            CompletedDate = new DateTime(2024, 7, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6187),
                            ScheduledDate = new DateTime(2024, 7, 19, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6187),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 36,
                            ScheduledDate = new DateTime(2024, 8, 14, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6189),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 37,
                            ScheduledDate = new DateTime(2024, 8, 12, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6191),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 38,
                            ScheduledDate = new DateTime(2024, 8, 21, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6192),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 39,
                            ScheduledDate = new DateTime(2024, 8, 4, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6193),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 40,
                            ScheduledDate = new DateTime(2024, 8, 1, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6194),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 41,
                            CompletedDate = new DateTime(2024, 7, 26, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6196),
                            ScheduledDate = new DateTime(2024, 7, 21, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6196),
                            ServiceAdvisorId = 2,
                            Status = 2,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 42,
                            ScheduledDate = new DateTime(2024, 8, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6197),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 43,
                            ScheduledDate = new DateTime(2024, 8, 8, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6199),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        },
                        new
                        {
                            Id = 44,
                            ScheduledDate = new DateTime(2024, 8, 22, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6201),
                            ServiceAdvisorId = 2,
                            Status = 1,
                            VehicleId = 1
                        },
                        new
                        {
                            Id = 45,
                            ScheduledDate = new DateTime(2024, 8, 13, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(6202),
                            ServiceAdvisorId = 2,
                            Status = 0,
                            VehicleId = 2
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobileNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2023, 11, 1, 13, 28, 12, 0, DateTimeKind.Unspecified),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "",
                            MobileNumber = "1234567890",
                            Password = "admin",
                            UserType = "ADMIN"
                        },
                        new
                        {
                            Id = 2,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 7, 29, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5153),
                            Email = "john.doe@example.com",
                            FirstName = "John",
                            LastName = "Doe",
                            MobileNumber = "0987654321",
                            Password = "password",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 3,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 7, 19, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5166),
                            Email = "jane.smith@example.com",
                            FirstName = "Jane",
                            LastName = "Smith",
                            MobileNumber = "2345678901",
                            Password = "password123",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 4,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 7, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5172),
                            Email = "emily.johnson@example.com",
                            FirstName = "Emily",
                            LastName = "Johnson",
                            MobileNumber = "3456789012",
                            Password = "password456",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 5,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 7, 14, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5174),
                            Email = "michael.williams@example.com",
                            FirstName = "Michael",
                            LastName = "Williams",
                            MobileNumber = "4567890123",
                            Password = "password789",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 6,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 7, 9, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5176),
                            Email = "sarah.brown@example.com",
                            FirstName = "Sarah",
                            LastName = "Brown",
                            MobileNumber = "5678901234",
                            Password = "password987",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 7,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 7, 4, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5178),
                            Email = "david.davis@example.com",
                            FirstName = "David",
                            LastName = "Davis",
                            MobileNumber = "6789012345",
                            Password = "password654",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 8,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 6, 29, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5180),
                            Email = "laura.wilson@example.com",
                            FirstName = "Laura",
                            LastName = "Wilson",
                            MobileNumber = "7890123456",
                            Password = "password321",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 9,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 6, 24, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5182),
                            Email = "daniel.moore@example.com",
                            FirstName = "Daniel",
                            LastName = "Moore",
                            MobileNumber = "8901234567",
                            Password = "password246",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 10,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 6, 19, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5184),
                            Email = "olivia.taylor@example.com",
                            FirstName = "Olivia",
                            LastName = "Taylor",
                            MobileNumber = "9012345678",
                            Password = "password135",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 11,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 6, 14, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5186),
                            Email = "ethan.anderson@example.com",
                            FirstName = "Ethan",
                            LastName = "Anderson",
                            MobileNumber = "0123456789",
                            Password = "password864",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 12,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 6, 9, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5187),
                            Email = "ava.thomas@example.com",
                            FirstName = "Ava",
                            LastName = "Thomas",
                            MobileNumber = "1234567890",
                            Password = "password753",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 13,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 6, 4, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5189),
                            Email = "james.jackson@example.com",
                            FirstName = "James",
                            LastName = "Jackson",
                            MobileNumber = "2345678901",
                            Password = "password642",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 14,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 5, 30, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5191),
                            Email = "isabella.white@example.com",
                            FirstName = "Isabella",
                            LastName = "White",
                            MobileNumber = "3456789012",
                            Password = "password531",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 15,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 5, 25, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5193),
                            Email = "benjamin.harris@example.com",
                            FirstName = "Benjamin",
                            LastName = "Harris",
                            MobileNumber = "4567890123",
                            Password = "password420",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 16,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 5, 20, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5195),
                            Email = "sophia.martin@example.com",
                            FirstName = "Sophia",
                            LastName = "Martin",
                            MobileNumber = "5678901234",
                            Password = "password309",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 17,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 5, 15, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5197),
                            Email = "jackson.thompson@example.com",
                            FirstName = "Jackson",
                            LastName = "Thompson",
                            MobileNumber = "6789012345",
                            Password = "password198",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 18,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 5, 10, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5199),
                            Email = "mia.garcia@example.com",
                            FirstName = "Mia",
                            LastName = "Garcia",
                            MobileNumber = "7890123456",
                            Password = "password987",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 19,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 5, 5, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5200),
                            Email = "alexander.martinez@example.com",
                            FirstName = "Alexander",
                            LastName = "Martinez",
                            MobileNumber = "8901234567",
                            Password = "password876",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 20,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 4, 30, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5202),
                            Email = "charlotte.roberts@example.com",
                            FirstName = "Charlotte",
                            LastName = "Roberts",
                            MobileNumber = "9012345678",
                            Password = "password765",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 21,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 4, 25, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5257),
                            Email = "henry.lee@example.com",
                            FirstName = "Henry",
                            LastName = "Lee",
                            MobileNumber = "0123456789",
                            Password = "password654",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 22,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 4, 20, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5260),
                            Email = "amelia.perez@example.com",
                            FirstName = "Amelia",
                            LastName = "Perez",
                            MobileNumber = "1234567890",
                            Password = "password543",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 23,
                            AccountStatus = "UNAPPROVED",
                            CreatedOn = new DateTime(2024, 4, 15, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5261),
                            Email = "sebastian.young@example.com",
                            FirstName = "Sebastian",
                            LastName = "Young",
                            MobileNumber = "2345678901",
                            Password = "password432",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 24,
                            AccountStatus = "APPROVED",
                            CreatedOn = new DateTime(2024, 4, 10, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5263),
                            Email = "harper.walker@example.com",
                            FirstName = "Harper",
                            LastName = "Walker",
                            MobileNumber = "3456789012",
                            Password = "password321",
                            UserType = "SERVICE_ADVISOR"
                        },
                        new
                        {
                            Id = 25,
                            AccountStatus = "SUSPENDED",
                            CreatedOn = new DateTime(2024, 4, 5, 22, 50, 30, 141, DateTimeKind.Local).AddTicks(5265),
                            Email = "oliver.hall@example.com",
                            FirstName = "Oliver",
                            LastName = "Hall",
                            MobileNumber = "4567890123",
                            Password = "password210",
                            UserType = "SERVICE_ADVISOR"
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vehicles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            LicensePlate = "ABC123",
                            Model = "Model X",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 2,
                            LicensePlate = "XYZ789",
                            Model = "Model Y",
                            OwnerId = 2
                        },
                        new
                        {
                            Id = 3,
                            LicensePlate = "LMN456",
                            Model = "Model Z",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 4,
                            LicensePlate = "PQR012",
                            Model = "Model A",
                            OwnerId = 3
                        },
                        new
                        {
                            Id = 5,
                            LicensePlate = "STU345",
                            Model = "Model B",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 6,
                            LicensePlate = "VWX678",
                            Model = "Model C",
                            OwnerId = 4
                        },
                        new
                        {
                            Id = 7,
                            LicensePlate = "YZA901",
                            Model = "Model D",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 8,
                            LicensePlate = "BCD234",
                            Model = "Model E",
                            OwnerId = 5
                        },
                        new
                        {
                            Id = 9,
                            LicensePlate = "EFG567",
                            Model = "Model F",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 10,
                            LicensePlate = "HIJ890",
                            Model = "Model G",
                            OwnerId = 6
                        },
                        new
                        {
                            Id = 11,
                            LicensePlate = "KLM123",
                            Model = "Model H",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 12,
                            LicensePlate = "NOP456",
                            Model = "Model I",
                            OwnerId = 7
                        },
                        new
                        {
                            Id = 13,
                            LicensePlate = "QRS789",
                            Model = "Model J",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 14,
                            LicensePlate = "TUV012",
                            Model = "Model K",
                            OwnerId = 8
                        },
                        new
                        {
                            Id = 15,
                            LicensePlate = "WXY345",
                            Model = "Model L",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 16,
                            LicensePlate = "ZAB678",
                            Model = "Model M",
                            OwnerId = 9
                        },
                        new
                        {
                            Id = 17,
                            LicensePlate = "CDE901",
                            Model = "Model N",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 18,
                            LicensePlate = "FGH234",
                            Model = "Model O",
                            OwnerId = 10
                        },
                        new
                        {
                            Id = 19,
                            LicensePlate = "IJK567",
                            Model = "Model P",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 20,
                            LicensePlate = "LMN890",
                            Model = "Model Q",
                            OwnerId = 11
                        },
                        new
                        {
                            Id = 21,
                            LicensePlate = "OPQ123",
                            Model = "Model R",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 22,
                            LicensePlate = "RST456",
                            Model = "Model S",
                            OwnerId = 12
                        },
                        new
                        {
                            Id = 23,
                            LicensePlate = "UVW789",
                            Model = "Model T",
                            OwnerId = 13
                        },
                        new
                        {
                            Id = 24,
                            LicensePlate = "XYZ012",
                            Model = "Model U",
                            OwnerId = 13
                        },
                        new
                        {
                            Id = 25,
                            LicensePlate = "ABC345",
                            Model = "Model V",
                            OwnerId = 14
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkItems", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Cost = 30.00m,
                            Name = "Oil Change"
                        },
                        new
                        {
                            Id = 2,
                            Cost = 40.00m,
                            Name = "Tire Rotation"
                        },
                        new
                        {
                            Id = 3,
                            Cost = 50.00m,
                            Name = "Brake Inspection"
                        },
                        new
                        {
                            Id = 4,
                            Cost = 70.00m,
                            Name = "Battery Replacement"
                        },
                        new
                        {
                            Id = 5,
                            Cost = 120.00m,
                            Name = "Engine Tune-Up"
                        },
                        new
                        {
                            Id = 6,
                            Cost = 150.00m,
                            Name = "Transmission Service"
                        },
                        new
                        {
                            Id = 7,
                            Cost = 60.00m,
                            Name = "Alignment"
                        },
                        new
                        {
                            Id = 8,
                            Cost = 20.00m,
                            Name = "Filter Replacement"
                        },
                        new
                        {
                            Id = 9,
                            Cost = 25.00m,
                            Name = "Fluid Check"
                        },
                        new
                        {
                            Id = 10,
                            Cost = 80.00m,
                            Name = "Suspension Check"
                        },
                        new
                        {
                            Id = 11,
                            Cost = 45.00m,
                            Name = "Headlight Replacement"
                        },
                        new
                        {
                            Id = 12,
                            Cost = 35.00m,
                            Name = "Tail Light Replacement"
                        },
                        new
                        {
                            Id = 13,
                            Cost = 100.00m,
                            Name = "Air Conditioning Service"
                        },
                        new
                        {
                            Id = 14,
                            Cost = 55.00m,
                            Name = "Radiator Flush"
                        },
                        new
                        {
                            Id = 15,
                            Cost = 75.00m,
                            Name = "Power Steering Service"
                        },
                        new
                        {
                            Id = 16,
                            Cost = 40.00m,
                            Name = "Serpentine Belt Replacement"
                        },
                        new
                        {
                            Id = 17,
                            Cost = 90.00m,
                            Name = "Water Pump Replacement"
                        },
                        new
                        {
                            Id = 18,
                            Cost = 200.00m,
                            Name = "Timing Belt Replacement"
                        },
                        new
                        {
                            Id = 19,
                            Cost = 85.00m,
                            Name = "Exhaust System Check"
                        },
                        new
                        {
                            Id = 20,
                            Cost = 95.00m,
                            Name = "Differential Service"
                        },
                        new
                        {
                            Id = 21,
                            Cost = 25.00m,
                            Name = "Windshield Wiper Replacement"
                        },
                        new
                        {
                            Id = 22,
                            Cost = 50.00m,
                            Name = "Rear Window Defogger Repair"
                        },
                        new
                        {
                            Id = 23,
                            Cost = 15.00m,
                            Name = "Fuse Replacement"
                        },
                        new
                        {
                            Id = 24,
                            Cost = 100.00m,
                            Name = "Wheel Bearing Replacement"
                        },
                        new
                        {
                            Id = 25,
                            Cost = 180.00m,
                            Name = "Turbocharger Service"
                        });
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceItem", b =>
                {
                    b.HasOne("Vehicle_Backend.Models.ServiceRecord", "ServiceRecord")
                        .WithMany()
                        .HasForeignKey("ServiceRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Vehicle_Backend.Models.WorkItem", "WorkItem")
                        .WithMany()
                        .HasForeignKey("WorkItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceRecord");

                    b.Navigation("WorkItem");
                });

            modelBuilder.Entity("Vehicle_Backend.Models.ServiceRecord", b =>
                {
                    b.HasOne("Vehicle_Backend.Models.User", "ServiceAdvisor")
                        .WithMany()
                        .HasForeignKey("ServiceAdvisorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vehicle_Backend.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceAdvisor");

                    b.Navigation("Vehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
